import type { BusinessSettings, Invoice, Order } from "@/types";
import { APP_CONFIG } from "@/config/app";

export const DEFAULT_SETTINGS: BusinessSettings = {
  legalBusinessName: "Northline Medical Supply Inc.",
  displayName: "Northline Medical Supply",
  businessEmail: "billing@northlinemedical.com",
  phone: "+1 (416) 555-0142",
  address: "220 Rivergate Way, Suite 400\nToronto, ON M5V 2T6\nCanada",
  taxId: "84-2910337",
  invoicePrefix: "INV",
  nextInvoiceNumber: 1043,
  defaultCurrency: APP_CONFIG.defaultCurrency,
  defaultTaxRate: APP_CONFIG.defaultTaxRate,
  defaultPaymentTerms: 30,
  paymentInstructions:
    "Payment by ACH or wire transfer within the stated terms. Reference the invoice number on all remittances.",
  footerNotes: "Thank you for your business. Questions? Reply to this email and our team will help.",
  primaryColor: "#1e3a5f",
  emailSubject: "Invoice {{invoice_number}} from {{business_name}}",
  emailGreeting: "Hello {{customer_name}},",
  emailBody:
    "Please find attached invoice {{invoice_number}} for order {{order_number}}, totalling {{amount}}. Payment is due within {{terms}} days.",
  emailClosing: "Kind regards,\nAccounts Receivable\nNorthline Medical Supply",
};

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const SEED_ORDERS: Order[] = [
  {
    id: "ord_seed_1001",
    orderNumber: "ORD-2026-0001",
    customerEmail: "purchasing@brightleafpharmacy.com",
    currency: "USD",
    dueInDays: 30,
    internalNotes: "Repeat customer. Ships from Toronto warehouse.",
    items: [
      {
        id: "itm_1001_1",
        description: "Pharmacy Refrigerator, 24 cu. ft. glass door",
        sku: "PHR-2400",
        quantity: 1,
        unitPrice: 4380,
        taxable: true,
      },
      {
        id: "itm_1001_2",
        description: "Delivery and Installation",
        sku: "SRV-INST",
        quantity: 1,
        unitPrice: 425,
        taxable: false,
      },
    ],
    discountType: "percentage",
    discountValue: 5,
    taxRate: 8.25,
    shipping: 0,
    status: "delivered",
    token: "s3edtoken0001brightleafpharmacyorderlink",
    createdAt: daysAgo(24),
    updatedAt: daysAgo(19),
    timeline: [
      { status: "draft", at: daysAgo(24) },
      { status: "link_sent", at: daysAgo(24) },
      { status: "form_opened", at: daysAgo(23) },
      { status: "submitted", at: daysAgo(23) },
      { status: "invoice_generated", at: daysAgo(22) },
      { status: "email_sent", at: daysAgo(22) },
      { status: "delivered", at: daysAgo(19) },
    ],
    customerInformation: {
      fullName: "Dana Whitfield",
      email: "purchasing@brightleafpharmacy.com",
      phone: "+1 (312) 555-0188",
      legalBusinessName: "Brightleaf Pharmacy Group LLC",
      operatingName: "Brightleaf Pharmacy #12",
      poNumber: "PO-77413",
      billingAddress: {
        line1: "1188 W Kinzie St",
        line2: "Floor 3",
        city: "Chicago",
        region: "IL",
        postalCode: "60642",
        country: "United States",
      },
      shippingAddress: {
        line1: "1188 W Kinzie St",
        line2: "Floor 3",
        city: "Chicago",
        region: "IL",
        postalCode: "60642",
        country: "United States",
      },
      shippingSameAsBilling: true,
      confirmedAccurate: true,
      confirmedAuthorized: true,
      submittedAt: daysAgo(23),
    },
  },
  {
    id: "ord_seed_1002",
    orderNumber: "ORD-2026-0002",
    customerEmail: "accounts@harbourclinic.ca",
    currency: "USD",
    dueInDays: 15,
    internalNotes: "Clinic expansion order.",
    items: [
      {
        id: "itm_1002_1",
        description: "Examination Table, powered hi-lo",
        sku: "EXT-500P",
        quantity: 3,
        unitPrice: 2190,
        taxable: true,
      },
      {
        id: "itm_1002_2",
        description: "Narcotic Safe, TL-15 rated",
        sku: "NRS-115",
        quantity: 1,
        unitPrice: 1875,
        taxable: true,
      },
    ],
    discountType: "fixed",
    discountValue: 250,
    taxRate: 8.25,
    shipping: 320,
    status: "submitted",
    token: "s3edtoken0002harbourclinicorderlinkabcd1",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
    timeline: [
      { status: "draft", at: daysAgo(6) },
      { status: "link_sent", at: daysAgo(6) },
      { status: "form_opened", at: daysAgo(5) },
      { status: "submitted", at: daysAgo(4) },
    ],
    customerInformation: {
      fullName: "Marcus Lai",
      email: "accounts@harbourclinic.ca",
      phone: "+1 (604) 555-0111",
      legalBusinessName: "Harbour Clinic Health Services Ltd.",
      operatingName: "Harbour Clinic",
      poNumber: "",
      billingAddress: {
        line1: "77 Seymour Street",
        city: "Vancouver",
        region: "BC",
        postalCode: "V6B 3H4",
        country: "Canada",
      },
      shippingAddress: {
        line1: "77 Seymour Street",
        city: "Vancouver",
        region: "BC",
        postalCode: "V6B 3H4",
        country: "Canada",
      },
      shippingSameAsBilling: true,
      confirmedAccurate: true,
      confirmedAuthorized: true,
      submittedAt: daysAgo(4),
    },
  },
  {
    id: "ord_seed_1003",
    orderNumber: "ORD-2026-0003",
    customerEmail: "ops@meridianrx.com",
    currency: "USD",
    dueInDays: 30,
    internalNotes: "Awaiting billing contact details.",
    items: [
      {
        id: "itm_1003_1",
        description: "Narcotic Safe, wall-anchored",
        sku: "NRS-080",
        quantity: 2,
        unitPrice: 1290,
        taxable: true,
      },
      {
        id: "itm_1003_2",
        description: "Delivery and Installation",
        sku: "SRV-INST",
        quantity: 1,
        unitPrice: 380,
        taxable: false,
      },
    ],
    discountType: "fixed",
    discountValue: 0,
    taxRate: 8.25,
    shipping: 145,
    status: "link_sent",
    token: "s3edtoken0003meridianrxorderlinkefgh234",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    timeline: [
      { status: "draft", at: daysAgo(2) },
      { status: "link_sent", at: daysAgo(2) },
    ],
  },
  {
    id: "ord_seed_1004",
    orderNumber: "ORD-2026-0004",
    customerEmail: "billing@stonewaymedical.com",
    currency: "USD",
    dueInDays: 30,
    items: [
      {
        id: "itm_1004_1",
        description: "Pharmacy Refrigerator, 12 cu. ft. undercounter",
        sku: "PHR-1200",
        quantity: 2,
        unitPrice: 2450,
        taxable: true,
      },
    ],
    discountType: "fixed",
    discountValue: 0,
    taxRate: 8.25,
    shipping: 210,
    status: "failed",
    token: "s3edtoken0004stonewaymedicalorderlinkij5",
    createdAt: daysAgo(11),
    updatedAt: daysAgo(9),
    timeline: [
      { status: "draft", at: daysAgo(11) },
      { status: "link_sent", at: daysAgo(11) },
      { status: "submitted", at: daysAgo(10) },
      { status: "invoice_generated", at: daysAgo(10) },
      { status: "failed", at: daysAgo(9), note: "Invoice email bounced (mailbox full)." },
    ],
    customerInformation: {
      fullName: "Priya Raman",
      email: "billing@stonewaymedical.com",
      phone: "+1 (206) 555-0134",
      legalBusinessName: "Stoneway Medical Partners Inc.",
      poNumber: "PO-2291",
      billingAddress: {
        line1: "915 Dexter Ave N",
        city: "Seattle",
        region: "WA",
        postalCode: "98109",
        country: "United States",
      },
      shippingAddress: {
        line1: "915 Dexter Ave N",
        city: "Seattle",
        region: "WA",
        postalCode: "98109",
        country: "United States",
      },
      shippingSameAsBilling: true,
      confirmedAccurate: true,
      confirmedAuthorized: true,
      submittedAt: daysAgo(10),
    },
  },
  {
    id: "ord_seed_1005",
    orderNumber: "ORD-2026-0005",
    customerEmail: "procurement@cedarvalleyclinic.com",
    currency: "USD",
    dueInDays: 45,
    items: [
      {
        id: "itm_1005_1",
        description: "Examination Table, manual",
        sku: "EXT-200M",
        quantity: 4,
        unitPrice: 985,
        taxable: true,
      },
    ],
    discountType: "percentage",
    discountValue: 10,
    taxRate: 8.25,
    shipping: 0,
    status: "draft",
    token: "s3edtoken0005cedarvalleyorderlinkklm678",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    timeline: [{ status: "draft", at: daysAgo(1) }],
  },
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: "inv_seed_1",
    invoiceNumber: "INV-01041",
    orderId: "ord_seed_1001",
    orderNumber: "ORD-2026-0001",
    customerEmail: "purchasing@brightleafpharmacy.com",
    customerName: "Brightleaf Pharmacy Group LLC",
    amount: 4906.03,
    currency: "USD",
    invoiceDate: daysAgo(22),
    emailStatus: "delivered",
  },
  {
    id: "inv_seed_2",
    invoiceNumber: "INV-01042",
    orderId: "ord_seed_1004",
    orderNumber: "ORD-2026-0004",
    customerEmail: "billing@stonewaymedical.com",
    customerName: "Stoneway Medical Partners Inc.",
    amount: 5514.25,
    currency: "USD",
    invoiceDate: daysAgo(10),
    emailStatus: "bounced",
  },
];